### ISSUE TITLE
packages/rocket:module/plugin/plugin.js:292:1: isopack-1 is undefined.

### ISSUE THREAD

**Issue by mbrookes** [trusktr/rocket-module#7]
```
=> Errors prevented startup:                  

   While loading plugin `rocket:module` from package `rocket:module`:
   packages/rocket:module/plugin/plugin.js:292:1: isopack-1 is undefined. Please report this issue. Thanks!
   at isoOrUni (packages/rocket:module/plugin/plugin.js:292:1)
   at getInfoFromIsopack (packages/rocket:module/plugin/plugin.js:355:1)
   at getPackageInfo (packages/rocket:module/plugin/plugin.js:490:1)
   at packages/rocket:module/plugin/plugin.js:186:1
   at arrayReduce
   (/Users/mbrookes/.meteor/packages/rocket_module/.0.1.5_5.1641otc++os+web.browser+web.cordova/plugin.rocket_module.os/npm/rocket_module/node_modules/lodash/index.js:1516:23)
   at Function.<anonymous>
   (/Users/mbrookes/.meteor/packages/rocket_module/.0.1.5_5.1641otc++os+web.browser+web.cordova/plugin.rocket_module.os/npm/rocket_module/node_modules/lodash/index.js:3505:13)
   at getDependentsOf (packages/rocket:module/plugin/plugin.js:185:1)
   at Package (packages/rocket:module/plugin/plugin.js:752:1)
   at Package (packages/rocket:module/plugin/plugin.js:845:1)
   at <runJavaScript-37>:865:4
   at <runJavaScript-37>:872:3

```

This is preceded by:

```
$ meteor --release PLUGINS-PREVIEW@2
=> Using PLUGINS-PREVIEW@2 as requested (overriding Meteor 1.1.0.3)

[[[[[ ~/Projects/simple-todos-react ]]]]]     

=> Started proxy.                             
=> Started MongoDB.                           

Changes to your project's package version selections:

accounts-base           upgraded from 1.2.0 to 1.2.1-plugins.0
accounts-password       upgraded from 1.1.1 to 1.1.2-plugins.0
accounts-ui             upgraded from 1.1.5 to 1.1.6-plugins.1
accounts-ui-unstyled    upgraded from 1.1.7 to 1.1.8-plugins.0
autoupdate              upgraded from 1.2.1 to 1.2.2-plugins.0
babel-compiler          upgraded from 5.6.15 to 5.8.3-plugins.0_5
babel-runtime           downgraded from 0.1.3 to 0.1.2
base64                  upgraded from 1.0.3 to 1.0.4-plugins.0
binary-heap             upgraded from 1.0.3 to 1.0.4-plugins.0
blaze                   upgraded from 2.1.2 to 2.1.3-plugins.0
blaze-tools             upgraded from 1.0.3 to 1.0.4-plugins.0
boilerplate-generator   upgraded from 1.0.3 to 1.0.4-plugins.0
caching-compiler        added, version 1.0.0-plugins.1
callback-hook           upgraded from 1.0.3 to 1.0.4-plugins.0
check                   upgraded from 1.0.5 to 1.0.6-plugins.0
coffeescript            upgraded from 1.0.6 to 1.0.7-plugins.1
ddp                     upgraded from 1.1.0 to 1.2.0-plugins.0
ddp-client              added, version 1.2.0-plugins.0
ddp-common              added, version 1.2.0-plugins.0
ddp-rate-limiter        added, version 0.0.1-plugins.0
ddp-server              added, version 1.2.0-plugins.1
deps                    upgraded from 1.0.7 to 1.0.8-plugins.0
diff-sequence           added, version 1.0.0-plugins.0
ecmascript              added, version 0.1.3-plugins.1
ejson                   upgraded from 1.0.6 to 1.0.7-plugins.0
email                   upgraded from 1.0.6 to 1.0.7-plugins.0
fastclick               upgraded from 1.0.3 to 1.0.6-plugins.0
geojson-utils           upgraded from 1.0.3 to 1.0.4-plugins.0
html-tools              upgraded from 1.0.4 to 1.0.5-plugins.0
htmljs                  upgraded from 1.0.4 to 1.0.5-plugins.0
http                    upgraded from 1.1.0 to 1.1.1-plugins.0
id-map                  upgraded from 1.0.3 to 1.0.4-plugins.0
jquery                  downgraded from 1.11.3_2 to 1.11.3-plugins.0_3
json                    upgraded from 1.0.3 to 1.0.4-plugins.0
launch-screen           upgraded from 1.0.2 to 1.0.3-plugins.0
less*                   upgraded from 1.0.14 to 2.5.0-plugins.0_2
livedata                upgraded from 1.0.13 to 1.0.14-plugins.0
localstorage            upgraded from 1.0.3 to 1.0.4-plugins.0
logging                 upgraded from 1.0.7 to 1.0.8-plugins.0
meteor                  upgraded from 1.1.6 to 1.1.7-plugins.1
meteor-platform         upgraded from 1.2.2 to 1.2.3-plugins.0
minifiers               upgraded from 1.1.5 to 1.1.6-plugins.0
minimongo               upgraded from 1.0.8 to 1.0.9-plugins.0
mobile-status-bar       upgraded from 1.0.3 to 1.0.4-plugins.0
mongo                   upgraded from 1.1.0 to 1.1.1-plugins.0
mongo-id                added, version 1.0.0-plugins.0
npm-mongo               added, version 1.4.32-plugins.0_1
observe-sequence        upgraded from 1.0.6 to 1.0.7-plugins.0
ordered-dict            upgraded from 1.0.3 to 1.0.4-plugins.0
package-version-parser  upgraded from 3.0.3 to 3.0.4-plugins.0
promise                 added, version 0.4.2-plugins.0
random                  upgraded from 1.0.3 to 1.0.4-plugins.0
rate-limit              added, version 0.0.1-plugins.0
reactive-dict           upgraded from 1.1.0 to 1.1.1-plugins.0
reactive-var            upgraded from 1.0.5 to 1.0.6-plugins.0
reload                  upgraded from 1.1.3 to 1.1.4-plugins.0
retry                   upgraded from 1.0.3 to 1.0.4-plugins.0
routepolicy             upgraded from 1.0.5 to 1.0.6-plugins.0
service-configuration   upgraded from 1.0.4 to 1.0.5-plugins.0
session                 upgraded from 1.1.0 to 1.1.1-plugins.0
sha                     upgraded from 1.0.3 to 1.0.4-plugins.0
spacebars               upgraded from 1.0.6 to 1.0.7-plugins.0
spacebars-compiler      upgraded from 1.0.6 to 1.0.7-plugins.1
srp                     upgraded from 1.0.3 to 1.0.4-plugins.0
templating              upgraded from 1.1.1 to 1.1.2-plugins.1
tracker                 upgraded from 1.0.7 to 1.0.8-plugins.0
ui                      upgraded from 1.0.6 to 1.0.7-plugins.0
underscore              upgraded from 1.0.3 to 1.0.4-plugins.0
url                     upgraded from 1.0.4 to 1.0.5-plugins.0
webapp                  upgraded from 1.2.0 to 1.2.1-plugins.0
webapp-hashing          upgraded from 1.0.3 to 1.0.4-plugins.0

* These packages have been updated to new versions that are not backwards
compatible.
```

This is an existing project to which I've simply added rocket:module, an npm.json with one module:

```
{
  "fixed-data-table": "^0.4.6"
}
```

And an entry.js in the root of the project:

```
var FixedDataTable = require('fixed-data-table');
```

**Comment by trusktr** [comment]
Hi @mbrookes. Are you installing from Atmosphere or pulling from GitHub? That error is due to the wrong combination of Meteor and `rocket:module` versions. The latest `rocket:module` now works with 1.2-rc.7 (or above, I think). So, you can update your project with `meteor update --release 1.2-rc.7` and then just run `meteor add rocket:module`. Does that work?

**Comment by mbrookes** [comment]
Installing from Atmosphere. Upgrading to 1.2-rc.7 just made things worse I'm afraid. Meteor runs, but I get a ton of errors in the client console:

```
Uncaught Error: GroundDB cannot access the DDP.Connection class
Uncaught TypeError: Cannot read property '_groundUtil' of undefined
Uncaught TypeError: Cannot read property 'Ground' of undefined
Uncaught ReferenceError: Template is not defined
Uncaught ReferenceError: MUI is not defined
[...] etc.
```

**Edit: known issue with GroundDB**: https://github.com/GroundMeteor/db/issues/121 - Not sure how that impacts rocket:module and the ability to even start Meteor (see below), but regardless I think I'm stuck at 1.1 for now.

Adding rocket:module, and meteor won't start at all.:

```
/Users/mbrookes/.meteor/packages/meteor-tool/.1.1.7-rc.7.1f892bj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
TypeError: Cannot call method 'displayName' of undefined
    at SourceProcessorSet.addLegacyHandler (/tools/isobuild/build-plugin.js:141:64)
    at /tools/isobuild/build-plugin.js:171:12
    at Function._.each._.forEach (/Users/mbrookes/.meteor/packages/meteor-tool/.1.1.7-rc.7.1f892bj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
[...] etc
```

**Comment by trusktr** [comment]
@mbrookes Does it work if you try without grounddb? Once at Meteor 1.2, simply adding rocket:module shouldn't affect anything unless you make entry points (entry.js files). Make sure you don't have the ecmascript or jsx packages, as rocket:module handles those things. 

Got a repo I can check out?

**Comment by mbrookes** [comment]
Thanks @trusktr - So... when remove GroundDB (and related code dependencies), then add rocket:module, I get the same error as I first reported:

```
While loading plugin `rocket:module` from package `rocket:module`:
   packages/rocket:module/plugin/plugin.js:292:1: isopack-1 is undefined.
```

Oddly, modifying any file (even adding or removing a blank line) causes Meteor to restart without the error, and the app is then partially working `Timer` works, `TimesView` doesn't, `Map` never did.

Since you mentioned jsx, I tried removing the official Meteor `react` package, but still no change to the above behaviour (errors on start, restarts after file change), and then lots of other things are inevitably broken...

I've put a copy of it in this state (but with `react` package still present) [here](https://github.com/mbrookes/racetime-rocket-module) if you fancied taking a look.

**Comment by trusktr** [comment]
@mbrookes Sorry for the late reply.I've deprecated `rocket:module` in favor of Meteor 1.3 `modules`.

**Comment by mbrookes** [comment]
@trusktr - no worries, thanks for your work on it!
